name: Continuous Integration

on:
  workflow_dispatch:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on:
  workflow_dispatch:
 ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version:
  workflow_dispatch:
 '17'
        distribution:
  workflow_dispatch:
 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests

